name: Build Docmost release

on:
  workflow_dispatch:
  schedule:
    - cron: '6 * * * *'  

permissions:
  contents: write
  packages: write

jobs:
  check-and-prepare:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_version.outputs.RELEASE_VERSION }}
      release_id: ${{ steps.get_release_id.outputs.RELEASE_ID }}
      needs_to_build: ${{ steps.check_build.outputs.NEEDS_TO_BUILD }}
    steps:
      - name: Get latest release version
        id: get_version
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/docmost/docmost/releases/latest | jq -r .tag_name)
          echo "RELEASE_VERSION=${LATEST_RELEASE}" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        run: |
          RELEASE_TAG="${{ steps.get_version.outputs.RELEASE_VERSION }}"
          RELEASE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG})
          if [ "$RELEASE_EXISTS" = "200" ]; then
            echo "Release already exists, skipping creation"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Release does not exist, will create"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if:  steps.check_release.outputs.exist == 'false'
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.RELEASE_VERSION }}
          name: Extracted Binaries ${{ needs.check-and-prepare.outputs.release_version }}
          body: |
            This release contains extracted binaries from the Penpot Docker images for multiple Linux architectures.
            Original release: https://github.com/penpot/penpot/releases/tag/${{ needs.check-and-prepare.outputs.release_version }}
          draft: false
          prerelease: false

      - name: Get Release ID
        id: get_release_id
        needs: check_release
        run: |
          RELEASE_TAG="${{ steps.get_version.outputs.RELEASE_VERSION }}"
          RELEASE_ID=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG} | jq -r .id)
          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_OUTPUT

      - name: Need to build
        id: check_build
        needs: get_release_id
        run: |
          ASSET_NAME="docmost.tar.gz"
          ASSET_EXISTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/${{ needs.get_release_id.outputs.get_release_id }}/assets | jq ".[] | select(.name==\"${ASSET_NAME}\") | .name")
          if [ "$ASSET_EXISTS" = "\"$ASSET_NAME\"" ]; then
            echo "Asset already exists, skipping extraction and upload"
            echo "NEEDS_TO_BUILD=false" >> $GITHUB_OUTPUT
          else
            echo "Asset does not exist, will build and upload"
            echo "NEEDS_TO_BUILD=true" >> $GITHUB_OUTPUT
          fi

  build-and-package:
    needs: check-and-prepare
    if: needs.check-and-prepare.outputs.needs_to_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Get the source
        run: |
          curl -sL https://github.com/docmost/docmost/archive/refs/tags/${{ needs.check-and-prepare.outputs.release_version }}.tar.gz | tar xz --strip-components 1
      
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Prepare dist artifact
        run: |
          mkdir -p docmost/apps/server
          mkdir -p docmost/apps/client
          mkdir -p docmost/packages/editor-ext
          mv apps/server/dist docmost/apps/server/dist
          mv apps/client/dist docmost/apps/client/dist
          mv apps/server/package.json docmost/apps/server/package.json

          mv packages/editor-ext/dist docmost/packages/editor-ext/dist
          mv packages/editor-ext/package.json docmost/packages/editor-ext/package.json

          mv package.json docmost/package.json
          mv/pnpm*.yaml docmost/
          mv .npmrc docmost/.npmrc

          mv patches docmost/patches
      
      - name: Compress artifact
        run: tar czf docmost.tar.gz docmost

      - name: Upload Release Asset
        if: steps.check_asset.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/gzip" \
            -T "docmost.tar.gz" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ needs.check-and-prepare.outputs.release_id }}/assets?name=docmost.tar.gz"
